# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzUMq4nYuY1EObFYloiV3d5Xb-kHNMo1
"""

a,b = 10,9
print(a+b)